Section "InputClass"
    Identifier "CRIXA pointer tuning"
    MatchIsPointer "on"
    Driver "libinput"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0"
    Option "NaturalScrolling" "false"
EndSection

Section "InputClass"
    Identifier "CRIXA keyboard tuning"
    MatchIsKeyboard "on"
    Option "AutoRepeat" "250 40"
EndSection
